---
kind: pipeline
type: kubernetes
name: build
steps:
- name: image
  image: images.home.mtaylor.io/drone-kaniko:latest
  settings:
    repo: images.home.mtaylor.io/api-mtaylor-io
    auto_tag: true
    enable_cache: true
    username: anonymous
    password: anonymous
    registry: images.home.mtaylor.io
- name: deploy
  image: images.home.mtaylor.io/deployer:latest
  commands:
  - set -u
  - mkdir -p ~/.ssh
  - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  - git clone git@github.com:mtaylor91/argocd-deployment.git
  - cd argocd-deployment
  - env | sort
trigger:
  event:
  - push
  - tag
  - custom
---
kind: pipeline
type: kubernetes
name: promote
steps:
- name: release
  image: images.home.mtaylor.io/deployer:latest
  commands:
  - set -u
  - git fetch origin 'refs/tags/*:refs/tags/*'
  - git fetch origin $${DRONE_BRANCH}
  - export tag=$(get-release-tag)
  - cd deploy
  - kustomize edit set image images.home.mtaylor.io/mtaylor.io:$${tag}
  - cd ../
  - git commit -a -m v$${tag}
  - git tag $${tag}
  - git push origin $${tag}
trigger:
  event:
  - promote
  target:
  - production
